rodennis/RNLH

README.md

merge from development update README.md

merge from development update README.md

---

.gitignore
README.md
controllers/products.js
controllers/users.js
db/connection.js
package-lock.json
package.json
server.js

created file structure for backend, setup mongoDB connection

created file structure for backend, setup mongoDB connection

---

models/product.js
models/user.js

set up product model and user model

set up product model and user model

---

controllers/users.js
routes/index.js
routes/products.js
routes/users.js
seed/data.js

add routes for products and users

add routes for products and users

---

package.json

fix bug in package.json

---

helpers/restrict.js

add helpers file & restrict.js function

add helpers file & restrict.js function

---

package-lock.json
package.json

add jsonwebtoken dependency

---

package-lock.json
package.json

update main branch

---

package-lock.json
package.json

add bcrypt dependency

---

models/product.js

update syntax on product model

update syntax on product model

---

seed/data.js

add product to data.js

---

seed/data.js

created multiple products

---

controllers/users.js

updated token key

---

package.json

added db seed to scripts

---

seed/data.js

added data to seed/data.js

---

client/src/components/Carousel/Carousel.jsx
client/src/components/ContactCards/ContactCards.jsx
client/src/components/Footer/Footer.jsx
client/src/components/Layout/Layout.jsx
client/src/components/Nav/Nav.jsx
client/src/components/ProductCards/ProductCards.jsx
client/src/screens/AddProducts/AddProducts.jsx
client/src/screens/Contact/Contact.jsx
client/src/screens/EditProducts/EditProducts.jsx
client/src/screens/Home/Home.jsx
client/src/screens/ProductDetails/ProductDetails.jsx
client/src/screens/Products/Products.jsx
client/src/screens/SignIn/SignIn.jsx
client/src/screens/SignOut/SignOut.jsx
client/src/screens/SignUp/SignUp.jsx

add boilerplate to jsx files

---

netlify.toml

fix spacing error

---

client/package-lock.json
client/package.json
client/src/services/products.js
client/src/services/users.js

add apiConfig, products and users files

add apiConfig, products and users files

---

client/src/App.js

clear boilerplate

---

client/src/App.js
client/src/components/Layout/Layout.jsx
client/src/index.js
client/src/screens/AddProducts/AddProducts.jsx
client/src/screens/Contact/Contact.jsx
client/src/screens/EditProducts/EditProducts.jsx

add form for new products and updates & contact page info

add form for new products and updates & contact page info

---

client/src/screens/SignIn/SignIn.jsx
client/src/screens/SignOut/SignOut.jsx
client/src/screens/SignUp/SignUp.jsx

set up sign in, sign out, and sign up forms

 set up sign in, sign out, and sign up forms

---

client/src/App.js
client/src/components/Nav/Nav.jsx
client/src/components/ProductCards/ProductCards.jsx
client/src/index.js
client/src/screens/Products/Products.jsx

cleaned up some syntax

---

client/src/App.js
client/src/screens/ProductDetails/ProductDetails.jsx

syntax updates

---

client/src/App.js
client/src/screens/ProductDetails/ProductDetails.jsx

add error handling to productDetails page

add error handling to productDetails page

---

client/src/App.js
client/src/screens/Contact/Contact.jsx
client/src/screens/ProductDetails/ProductDetails.jsx

syntax update

---

client/src/App.js
client/src/screens/AddProducts/AddProducts.jsx
client/src/screens/EditProducts/EditProducts.jsx
client/src/screens/Home/Home.jsx
client/src/screens/ProductDetails/ProductDetails.jsx
client/src/screens/SignUp/SignUp.jsx

update to sign up

---

client/src/components/Footer/Footer.css
client/src/components/Footer/Footer.jsx

Just having a wack CSS problem.

Footer works

---

client/src/App.js
client/src/components/Carousel/Carousel.jsx

updated app.js and deleted unused component from Carousel

updated app.js and deleted unused component from Carousel

---

client/public/index.html
client/src/components/Footer/Footer.css
client/src/components/Footer/Footer.jsx
client/src/components/Nav/Nav.css
client/src/components/ProductCards/ProductCards.css

style footer, add italiana font family

style footer, add italiana font family

---

client/src/components/Carousel/Carousel.css
client/src/screens/Home/Home.css
client/src/screens/Home/Home.jsx

add styling to home page

---

client/src/App.js

update add & edit routes

---

client/src/App.js

add setToggle for add & edit routes

add setToggle for add & edit routes

---

client/src/App.js

update to setToggle

---

client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

fixed product details CSS

---

client/src/components/ProductCards/ProductCards.jsx

add key to products map in productCard,jsx

add key to products map in productCard,jsx

---

client/src/components/Layout/Layout.jsx
client/src/components/ProductCards/ProductCards.jsx

merge development into main

---

client/src/screens/AddProducts/AddProducts.jsx

add layout to add new product page

add layout to add new product page

---

client/src/components/Nav/Nav.css

change letter-spacing on navbar elements

change letter-spacing on navbar elements

---

client/src/components/Nav/Nav.css
client/src/components/Nav/Nav.jsx

changed media query sizing

---

client/src/App.js
client/src/components/Nav/Nav.jsx
client/src/components/ProductCards/ProductCards.css
client/src/screens/Products/Products.jsx

add product card responsivness

add product card responsivness

---

client/src/screens/AddProducts/AddProducts.css
client/src/screens/Contact/Contact.css
client/src/screens/EditProducts/EditProducts.css

add responsive css to add, edit & contact pages

add responsive css to add, edit & contact pages

---

client/src/components/Nav/Nav.css
client/src/components/Nav/Nav.jsx

fixed hamburger menu bug

---

client/src/screens/ProductDetails/ProductDetails.jsx

delete duplicate details

---

client/src/App.js
client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

create edit and delete for product details

create edit and delete for product details

---

client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

work on details css

---

client/src/screens/Home/Home.jsx

add guarding to id

---

client/src/screens/EditProducts/EditProducts.css
client/src/screens/Home/Home.jsx
client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

update product-details css

---

client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

Product Details Complete

---

client/src/components/Nav/Nav.css

change hamburger menu white

---

client/src/components/ProductCards/ProductCards.css
client/src/components/ProductCards/ProductCards.jsx
client/src/screens/ProductDetails/ProductDetails.css

change product card design

---

client/src/components/ProductCards/ProductCards.jsx
client/src/screens/ProductDetails/ProductDetails.jsx

add dynamic price to product cards and product details

add dynamic price to product cards and product details

---

client/src/screens/ProductDetails/ProductDetails.jsx

move price tag in product details

move price tag in product details

---

client/src/components/ProductCards/ProductCards.css
client/src/components/ProductCards/ProductCards.jsx

fix missing code in productCard.jsx and productCard.css

fix missing code in productCard.jsx and productCard.css

---

client/src/components/ProductCards/ProductCards.css
client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

edit details css and media queries

edit details css and media queries

---

client/src/components/ProductCards/ProductCards.css
client/src/components/ProductCards/ProductCards.jsx
client/src/screens/ProductDetails/ProductDetails.css
client/src/screens/ProductDetails/ProductDetails.jsx

merge development to main

---

client/src/screens/ProductDetails/ProductDetails.jsx

update price in productDetails.jsx

update price in productDetails.jsx
